name: "gs-sds-threefuse-multi"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-multiview-datamodule"
data:
  batch_size: 2
  width: 512
  height: 512
  camera_distance_range: [1.4, 1.4]
  fovy_range: [60, 70]
  elevation_range: [0, 90]
  light_sample_strategy: "dreamfusion"
  eval_camera_distance: 1.4
  eval_fovy_deg: 70
  rays_d_normalize: false
  num_multiview: 2
  multiview_deg: 30.0


system_type: "gaussian-splatting-noising-system"
system:
  image_dir: "/home/dreamer/host_files/matthew/matt_threestudio/threestudio/tower.png"
  threefuse: true
  three_noise: true
  identical_noising: true
  gaussian_dynamic: true
  geometry_type: "gaussian-splatting"
  calibration_value: 0
  geometry:
    position_lr_init: 0.001
    position_lr_final: 0.00002
    position_lr_delay_mult: 0.02
    position_lr_max_steps: 1000
    scale_lr_init: 0.005
    scale_lr_final: 0.005
    scale_lr_max_steps: ${trainer.max_steps}
    feature_lr: 0.01
    opacity_lr: 0.05
    scaling_lr: 0.005
    rotation_lr: 0.005
    densification_interval: 500
    prune_interval: 500
    opacity_reset_interval: 50000000
    densify_from_iter: 0
    densify_until_iter: 10000
    prune_from_iter: 1000
    prune_until_iter: ${trainer.max_steps}
    densify_grad_threshold: 0.01
    min_opac_prune: 0.005
    split_thresh: 0.01
    radii2d_thresh: 1000

    init_num_pts: 4096
    pc_init_radius: 0.8
    opacity_init: 0.2

  renderer_type: "diff-gaussian-rasterizer"
  renderer:
    debug: false
    invert_bg_prob: 0.5
    # scaling_modifier: 1.0

  material_type: "no-material" # unused
  material:
    n_output_dims: 0

  background_type: "solid-color-background" # unused

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
    pretrained_model_name_or_path_aux: "stabilityai/stable-diffusion-2-1"
    prompt: ???
    front_threshold: 30.
    back_threshold: 30.
    multiple_encoders: true

  guidance_type: "threefuse-multi-guidance"
  guidance:
    pretrained_model_name_or_path: "/mnt/data3/ines/threestudio/controlnet"
    guidance_scale: 100.0
    weighting_strategy: sds
    min_step_percent: 0.02
    max_step_percent: [2000, 0.98, 0.5, 2001]

  exporter_type: "gaussian-mesh-exporter"

  loggers:
    wandb:
      enable: false
      project: 'threestudio'
      name: None

  loss:
    lambda_sds: 0.1
    lambda_position: 1.0
    lambda_opacity: 0.0001
    lambda_scales: 0.0001
    lambda_tv_loss: 1.0
    lambda_depth_tv_loss: 1.0

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 250
  enable_progress_bar: true
  precision: 32-true
  # deterministic: true

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
